events {}

http {
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=100r/m;

    log_format api_logs '$time_local | $remote_addr | $request_method | $uri | $status';
    access_log /var/log/nginx/access.log api_logs;

    server {
        listen 80;

        # Auth Service
        location /api/auth/ {
            limit_req zone=api_limit burst=20 nodelay;
            proxy_pass http://auth-service:8001/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Resource Service
        location /api/resources/ {
            limit_req zone=api_limit burst=20 nodelay;
            proxy_pass http://resource-service:8002/resources/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Notification Service sin slash final
        location = /api/notifications {
            limit_req zone=api_limit burst=20 nodelay;
            proxy_pass http://notification-service:8003/notifications;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Notification Service con slash final
        location /api/notifications/ {
            limit_req zone=api_limit burst=20 nodelay;
            proxy_pass http://notification-service:8003/notifications;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}